
// Data source: University of Nottingham Ningbo China official website
// https://www.nottingham.edu.cn/cn/course/list.aspx

export const UNNC_MAJORS = [
  "Aerospace Engineering",
  "Applied Linguistics",
  "Architectural Environment Engineering",
  "Architecture",
  "Big Data Management and Applications",
  "Business Administration",
  "Chemical Engineering",
  "Chemical Engineering and Technology",
  "Chemistry",
  "Civil Engineering",
  "Computer Science",
  "Computer Science with Artificial Intelligence",
  "Digital Screen Production",
  "Economics",
  "Electrical and Electronic Engineering",
  "Electrical Engineering",
  "English",
  "English Language and Applied Linguistics",
  "English with International Business",
  "Entrepreneurship and Innovation Management",
  "Environmental Engineering",
  "Environmental Science",
  "Finance and Investment",
  "Finance, Accounting and Management",
  "Financial Technology in Economics",
  "Geography",
  "Geospatial Engineering with BIM",
  "History",
  "Human Resource Management",
  "Industrial Design",
  "Intelligent Infrastructure and Management",
  "International Business",
  "International Business Economics",
  "International Business Management",
  "International Communications",
  "International Development",
  "International Higher Education",
  "International Management",
  "International Relations and World History",
  "International Studies",
  "International Studies with Spanish/German/French/Japanese/Chinese",
  "Interpreting and Translation, Mandarin and English",
  "Management Science",
  "Marketing",
  "Material Science and Engineering",
  "Mathematics with Applied Mathematics",
  "Mechanical Engineering",
  "Mechatronic Engineering",
  "Philosophy",
  "Politics and International Relations",
  "Product Design and Manufacture",
  "Professional Accounting",
  "Psychology",
  "Sociology",
  "Statistics",
  "Sustainable Energy and Building Technologies",
  "Teaching English to Speakers of Other Languages",
  "Urbanism and Sustainable Environments"
].sort();
