"""initial_tables

Revision ID: 9208edf71e58
Revises: 
Create Date: 2026-03-28 18:50:15.098226

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = '9208edf71e58'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('match_results',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('recommended_user_id', sa.UUID(), nullable=False),
    sa.Column('rank', sa.SmallInteger(), nullable=False),
    sa.Column('match_score', sa.Numeric(precision=5, scale=4), nullable=False),
    sa.Column('match_reasons', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('is_viewed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('match_score BETWEEN 0 AND 1', name='ck_match_results_score'),
    sa.CheckConstraint('rank IN (1, 2, 3)', name='ck_match_results_rank'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match_sessions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('question_count', sa.SmallInteger(), nullable=False),
    sa.Column('user_vector', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('completed_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('questioning', 'matching', 'completed')", name='ck_match_sessions_status'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('question_answers',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('phase', sa.String(length=10), nullable=False),
    sa.Column('round_number', sa.SmallInteger(), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('selected_option', sa.String(length=5), nullable=True),
    sa.Column('dimension', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('answered_at', sa.TIMESTAMP(timezone=True), nullable=True),
    sa.CheckConstraint("phase IN ('pre', 'ai')", name='ck_question_answers_phase'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_profiles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('skill_modeling', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('skill_coding', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('skill_writing', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('personality_leader', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('personality_supporter', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('personality_executor', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('strength_competition_count', sa.Integer(), nullable=True),
    sa.Column('strength_award_count', sa.Integer(), nullable=True),
    sa.Column('strength_ambition', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('strength_major_relevant', sa.Numeric(precision=4, scale=2), nullable=True),
    sa.Column('preferred_role', sa.String(length=20), nullable=True),
    sa.Column('raw_answers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('updated_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('personality_executor  BETWEEN 0 AND 10', name='ck_personality_executor'),
    sa.CheckConstraint('personality_leader    BETWEEN 0 AND 10', name='ck_personality_leader'),
    sa.CheckConstraint('personality_supporter BETWEEN 0 AND 10', name='ck_personality_supporter'),
    sa.CheckConstraint('skill_coding      BETWEEN 0 AND 10', name='ck_skill_coding'),
    sa.CheckConstraint('skill_modeling    BETWEEN 0 AND 10', name='ck_skill_modeling'),
    sa.CheckConstraint('skill_writing     BETWEEN 0 AND 10', name='ck_skill_writing'),
    sa.CheckConstraint('strength_ambition BETWEEN 0 AND 10', name='ck_strength_ambition'),
    sa.CheckConstraint('strength_award_count >= 0', name='ck_strength_award_count'),
    sa.CheckConstraint('strength_competition_count >= 0', name='ck_strength_competition_count'),
    sa.CheckConstraint('strength_major_relevant  BETWEEN 0 AND 10', name='ck_strength_major_relevant'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('grade', sa.String(length=20), nullable=False),
    sa.Column('major', sa.String(length=100), nullable=False),
    sa.Column('team_goal', sa.String(length=100), nullable=False),
    sa.Column('want_long_term', sa.Boolean(), nullable=False),
    sa.Column('gender_preference', sa.String(length=10), nullable=True),
    sa.Column('grade_preference', sa.String(length=20), nullable=True),
    sa.Column('contact_info', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    op.drop_table('user_profiles')
    op.drop_table('question_answers')
    op.drop_table('match_sessions')
    op.drop_table('match_results')
    # ### end Alembic commands ###
